version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: dim_date
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: dim_employee
    columns:
      - name: employee_id
        tests:
          - unique
          - not_null
  - name: dim_product
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
  - name: fact_inventory
    columns:
      - name: inventory_id
        tests:
          - unique
          - not_null